apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: fluentd
spec:
  selector:
    matchLabels:
      k8s-app: fluentd-logging
  template:
    metadata:
      labels:
        k8s-app: fluentd-logging
    spec:
      terminationGracePeriodSeconds: 30
      serviceAccountName: fluentd
      containers:
      - name: fluentd
        image: fluent/fluentd-kubernetes-daemonset:v1.10.3-debian-cloudwatch-1.0
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
          - containerPort: 24224
        volumeMounts:
          - name: config-volume
            mountPath: /fluentd/etc
      volumes:
        - name: config-volume
          configMap:
            name: fluentd-config
---
apiVersion: v1
kind: Service
metadata:
  name: fluentd
  namespace: fluentd
spec:
  type: ClusterIP
  selector:
    k8s-app: fluentd-logging
  ports:
    - protocol: TCP
      port: 24224
      targetPort: 24224