apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-load-balancer-controller
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::073813292468:role/AmazonEKSLoadBalancerControllerRole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-dynamodb
  namespace: wsc2024
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::073813292468:role/AccessDynamodbRole