apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: customer
  namespace: wsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: customer
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: customer
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: product
  namespace: wsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: product
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: product
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: order
  namespace: wsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: order
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: order