apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dbcred
  namespace: wsi
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: dbcred
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: rds!db-1736b550-35e9-4c69-a606-46cf691546ff