apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: wsi
spec:
  type: NodePort
  selector:
    app: customer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: product
  namespace: wsi
spec:
  type: NodePort
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: order
  namespace: wsi
spec:
  type: NodePort
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080